MOUSEKEY_ENABLE = no

DYNAMIC_MACRO_ENABLE = yes

# RGBLIGHT_ENABLE = yes
# RGBLIGHT_DRIVER = WS2812
# RGBLIGHT_ANIMATIONS = yes
# RGBLIGHT_TWINKLE = no
# RGBLIGHT_STARTUP_ANIMATION = no

CONSOLE_ENABLE = no
